apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    move2kube.konveyor.io/expose: "true"
  labels:
    move2kube.konveyor.io/service: {{ .Release.Name }}-move2kubeui
  name: {{ .Release.Name }}-move2kubeui
spec:
  replicas: 2
  selector:
    matchLabels:
      move2kube.konveyor.io/service: {{ .Release.Name }}-move2kubeui
  strategy: {}
  template:
    metadata:
      annotations:
        move2kube.konveyor.io/expose: "true"
      labels:
        move2kube.konveyor.io/service: {{ .Release.Name }}-move2kubeui
      name: {{ .Release.Name }}-move2kubeui
    spec:
      containers:
        - image: quay.io/konveyor/move2kube-ui:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: Always
          name: move2kubeui
          env:
            - name: MOVE2KUBEAPI
              value: http://{{ .Release.Name }}-move2kubeapi:8080
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
